### ISSUE TITLE
Add Perl Script Image to Composition

### ISSUE THREAD

**Issue by JonathonRichardson** [WNPRC-EHR-Services/lkpm-cli#1]
Now that the Perl Script image is working, it'll need to get added to the composition.  An example service that I have working right now can be seen below.

```
perlscripts:
  image: 'wnprcehr/ehrcron:v0.1.0'
  environment:
    TZ: America/Chicago
  volumes:
    - '${NETRC}:/root/netrc'
  depends_on:
    - labkey
    - mailserver
```

Note that this will include adding a `netrc` file to the default configuration.

In addition, you might consider creating a log file and mounting it in the container as `/var/log/syslog`, so that the log is available outside of the container.
